### ISSUE TITLE
请问更新Bangumi播放进度的功能怎么工作呀

### ISSUE THREAD

**Issue by Patrick-Ze** [plsy1/easybangumi#1]
~我还在酝酿思路，结果刚开始搜API呢，就发现已经有人写了……~

请问更新Bangumi播放进度的功能怎么工作呀？搜了一下`markplayed`，指向Plex，请问是在Plex中点击已看完（或者类似操作）实现的么？后续会考虑支持别的媒体服务器么（比如Emby/Jellyfin）

**Comment by plsy1** [comment]
我目前用的是emby，在测试的时候用的也是emby。不过最近没什么时间完善功能。
实现是通过emby的webhook，发送用户的标记为播放/未播放给本程序，然后进行处理的。

**Comment by Patrick-Ze** [comment]
好的，谢谢～
